### ISSUE TITLE
Review of D4.2.1

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/validation#175]
Relates to #151 

* Section 1
- [x] please comply to the temaple https://github.com/openETCS/validation/blob/master/Templates/VnVRprtTmplt-131101-02.tex or deliver all information requested in it

- [ ] please relate all requirements to the TSI-CCS and its documents

* Section 2
- [x] please comply to the temaple https://github.com/openETCS/validation/blob/master/Templates/VnVRprtTmplt-131101-02.tex or deliver all information requested in it

**Comment by janWelte** [comment]
Dear authors of D4.2.1,

if have final been able to finish the last quality check of the D4.2.1 report (sorry for the long delay). Overall the report is quite good and has a good quality.

Nevertheless, I've found one major issue concerning the missing Document Versioning and Modification History, which can be change quite fast by taking the information from the github log.
The list of minor issues below looks long, but is actually relatively small compared to the overall document.

@anacavalli and @nhnghia 
I would ask you to correct this small issues (as the case may be hand them over to the author of the respective section). 

If you habe any question I'm glad to assist you.

As I understand the report is ready to be signed after these corrections are made.

Comments||||||
---|---|---|---|---|---|
#|Reviewer|Page/õ/Req.|Maj/Min/Q|Comment|Answer|OK/NOK/OPEN
1|JW|3|Maj|Document Versioning and Modification History missing||
2|JW|3|Min|Abstract missing||
3|JW|6, line 4|Min|"typo: ""verificatoin"" -> verification"||
4|JW|6, line 5|Min|"typo: ""verificatoin"" -> verification"||
5|JW|6|Min|please clearly reference sectionsby number||
6|JW|6|Min|please give reference to Subset-026 at all items or non at all||
7|JW|7, line 7|Min|"""As model-checking techniques check exhaustively models,"" unclear formulation, should be presented in a moreentensive way to state the understanding of model-checking"||
8|JW|7|Min|"""Subset-026.4.4"" uncommon reference to Subset-026, please use a consistent style for references to subset-026"||
9|JW|8|Min|"""Subset-026-3.8"" is one typ of referencein this document to Subset-026, please use a consistent style for references to subset-026 over the whole document"||
10|JW|8|Min|"emty paragraph ""Method/Approach"" and unclear format for ""Model Checking using IF"". This subsection should be clearly structured showing:Purpose/Goal; Means; Method; Tool"||
11|JW|"8, paragraph ""Means"""|Min|"typo: ""descriptionin"" -> description in"||
12|JW|8|Min|"paragraph headline ""Summary"" is not related to subsection and missplaced, please introduce your results with relation to the work presented"||
13|JW|9|Min|Figure 2 is not referenced in the text, please provide a short explanation what is shown and how it relates to your results||
14|JW|10|Min|"""Subset-026.4.4"" uncommon reference to Subset-026, please use a consistent style for references to subset-026"||
15|JW|10|Min|"pharagraph ""summary"" is very short. A more detailed explanation would be needed to understand the work"||
16|JW|"10, paragraph""Goal"""|Min|Subset-026-3.8 uncommon reference to Subset-026, please use a consistent style for references to subset-026||
17|JW|10|Min|"empty paragraph ""Method/Approach"" and unclear format for ""Test Generation using TestGen-IF"". This subsection should be clearly structured showing: Purpose/Goal; Means; Method; Tool"|
18|JW|11|Min|"""We have identified a set of basic requirements"" please give a clear reference to this requirements and classify them in your overall work"||
19|JW|11|Min|"""TestGen-IF tool automatically generates a set of test cases. "" please provide more details concerning the used test generation methodology"||
20|JW|"11, paragraph ""Summary"""|Min|"European Train Control System, ETCS has been used as an abbreviation before, therefore please continue to do so in the whole report"||
21|JW|"11, paragraph ""Evidence Produced"""|Min|"""compares the expected trace with trace that was simulated"" difficult to understand, "" found some inconsistencies "" what was the reason and how have they been resolved compared to SUBSET-026"||
22|JW|13|Min|footnote should be avoided and can in this case be integrated into the text||
23|JW|13|Min|Subset 026-5 uncommon reference to Subset-026, please use a consistent style for references to Subset-026 in all parts of the document (applies to more points of Section 3)||
24|JW|"15, ""Summary"""|Min|"""During the modeling we discovered 36 inconsistencies, ambiguities and gaps in the specification which we reported in [11]. "" sentence is already on page 14"||
25|JW|18|Min|"""(Uni Bremen/DLR) [21]"" missing. At the end of the sentence"||
26|JW|18|Min|"""The generated tests w"" sentence is incomplete"||
27|JW|18|Min|"""SUBSET-026[1] chap 3.5 [22]."" uncommon to reference a section of a document as a separate source"||
28|JW|20|Min|"""example the REQ-3.5.10"" (does not exist in SUBSET-026) is describe but ""REQ-3.5.3.10"" is listed below. Please, ensure consistency."||
29|JW|20|Min|"typo: ""Modified condtion"" ->Modified condition"||
30|JW|20|Min|"""Modified condition/decision coverage (MC/DC): Modified condition/decision coverage."" as all other coverage strategies are explained in a short way, it would be consistent to also do this with MC/DC"||
31|JW|20|Min|"""We then apply a requirement coverage strategy that consists of generating tests that covers all the requirements. "" please check this sentence"||
32|JW|20|Min|"""As each requirement are linked"", here it must be is"||
33|JW|21|Min|"""Total Requirements cover 40"" is miss place next to Table 1 and without relation to the following paragraph"||
34|JW|22|Min|"""Moreover some missing information in the specification leads to a under constraints test model."" please check sentence"||
35|JW|27ff|Min|footnotes should be avoided and can in this case be integrated into the text||
36|JW|29|Min|"""CENELEC norm"", please use a more precise reference, which at least gives a type and number of a specific standard (e.g. EN 50128)"||
37|JW|28ff|Min|"In subsection""6.1.2 Tools for verification"" not all paragraph headers are separated from the following text. Please use a consistent style for all paragraphs"||
38|JW|29-30|Min|Table 2 and the corresponding text are more related to the content of 6.1.1. Maybe these part should be shifted to this subsection||
39|JW|32|Min|empty paragraph{Formal proof results}, should not be in a line with the next subsection||
40|JW|32|Min|"typo: ""sepcified"" -> specified"||
41|JW|32|Min|"""according"" -> according to"||
42|JW|36|Min|"""i.e., "" comma is misplaced"||
43|JW|37 & 38|Min|"""To achieve this, we use the direct connection of the Event-B model with the ProR based on an EMF model of the Event-B model."" please check sentence, as it is difficult to understand"||
44|JW|38|Min|"""SS 026 section 3.5"" uncommon reference to Subset-026, please use a consistent style for references to subset-026"||
45|JW|41|Min|"""Quick Check tool available in the publisher"" could be helpful for a read not knowing SCADE to reference the publisher more specific."||
46|JW|43|Min|footnote should be avoided and can in this case be integrated into the text||
47|JW|43, subsection 7.2|Min|link is over text limit, please enforce a line change (by manual introduction of a breaking point)||
48|JW|43|Min|other parts of the report use the full word Figure for reference (instead of  Fig. 14), please be consistent||
49|JW|48 & 49|Min|"add reference for ""Subset 026"", respectively [1] "||
50|JW|48, subsection 7.6|Min|"please check whether this is just a wandering letter ""? model. s The?"" "||
51|JW|49|Min|"""This Deliverable .."" -> This deliverable ?"||
52|JW|49|Min|"typo ""Science & Inovation"" -> Science & Innovation"||
53|JW|49, section 8|Min|"""SRSs"" term has not been introduced before. Usually, only the SUBSET-026 itself is referred to as SRS. Please check this sentence."||
54|JW||Min|"""The V&V have been done on these models. They resulted the correctness of the SRS but also some inconsistencies, ambiguities and gaps in SRS being repported in the Specification Findings."" Please check sentences for correct gramatic. The meaning is not clear."||
55|JW|50|Min|"typo ""repported"" -> reported"||

**Comment by nhnghia** [comment]
Dear Jan,
Thank you for your very detail comments. 
A new version has been committed.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [validation] Review of D4.2.1 (#175)" gesendet am 12.06.2015 17:02:47. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.
