### ISSUE TITLE
Safety Plan: Chapter 3 - Lifecycle / chapter structure

### ISSUE THREAD

**Issue by ghost** [openETCS/validation#195]
Chapter strucure:

-The Safety plan should reference to each phase (subchapter) of the System and Software Lifecycle.
-It should be defined, what documents are necessary as input for a phase
-It should be defined, what documents has to be done in the phase
-It should be defined, what documents are to be created in the phase
-It should be defined, what exit criteria have to be met, in order to complete a phase (Review, Test etc..)

**Comment by janWelte** [comment]
|Reviewer|Page/õ/Req.|Maj/Min/Q|Comment|Answer|OK/NOK/OPEN
|--- |--- |--- |--- |--- |---
|SJ|Chapter strucure:||-The Safety plan should reference to each phase (subchapter) of the System and Software Lifecycle.|As this document is not the full safety plan itself, this points can not be addressed at the current state. They will be handled as far as possible in the future work.|NOK
|SJ|Chapter strucure:||-It should be defined, what documents are necessary as input for a phase|Will be address in the upcoming work|NOK
|SJ|Chapter strucure:||-It should be defined, what documents has to be done in the phase|Will be address in the upcoming work|Ok
|SJ|Chapter strucure:||-It should be defined, what documents are to be created in the phase|Will be address in the upcoming work|Ok
|SJ|Chapter strucure:||-It should be defined, what exit criteria have to be met, in order to complete a phase (Review, Test etc..)|Can not be specified here as this has to be defined in detail based on the concrete steps|Open
|SJ|Described Lifecycle:||-The stated lifecycle is ambigues. Its not clearly divided what is System and what is Software development|Changed text in section formalization and software development to emphasis that openETCs only does software development and just processes input from the overall ETCS system development|OK
|SJ|Described Lifecycle:||"-It ""seems"" to be compliant to the SW Lifecycle (EN50128 - Figure 4), but Reference to the Standards are missing"|Added number of direct references to the standard, but this will mainly be done in the detailed description of the process|Ok
|SJ|Overall Lifecycle:||-An overall Lifecycle should be defined (System development)|Only a Software lyfecycle is context of openETCS. This has to be defined in the Development documents|Open
|SJ|Overall Lifecycle:||-The Overall lifecycle should have an interface to the Software-Lifecycle (usually Apportionment of System Requirements)|Here the appointment of Subset 26 and other requirements to the software is the interface to the overall life cycle. Text and figure 7 has been modified to address this point.|Ok
|SJ|Overall Lifecycle:||-The overall Lifecycle should have references to the standards (EN50126/50129)|Only a Software lyfecycle is context of openETCS. This has to be defined in the Development documents|Open
